CREATE TABLE "GCG_3613_CONTAINER"(
 "CONTAINER" CHAR(15),
 "PURCHASE_ORDER" CHAR(7),
 "INVOICE_NO" CHAR(6),
 "DUTIABLE_VALUE" NUMERIC(15,4),
 "HARBOR_FEE" NUMERIC(15,4),
 "ZONE_ADMISSION" CHAR(17));

 CREATE TABLE "GCG_3613_ESTID"(
 "ESTID" CHAR(12));

 CREATE TABLE "GCG_3613_ForeignPart"(
 "PART" CHAR(17),
 "REV" CHAR(3),
 "LOC" CHAR(2),
 "HTSUS_NO" VARCHAR(12),
 "HTSUS_RATE" NUMERIC(8,4),
 "HTSUS_DESC" VARCHAR(30),
 "HTSUS_WEIGHT" NUMERIC(8,4),
 "CONVERSION_FACTOR" NUMERIC(14,8),
 "HTSUS_UM" VARCHAR(6),
 "AD_CVD_CASE" VARCHAR(20),
 "AD_CVD_RATE" NUMERIC(8,4),
 "FORM_ID" VARCHAR(5),
 "ORIGIN_COUNTRY" CHAR(2),
 "LOC_CODE" VARCHAR(6),
 "ZONE_STATUS" CHAR(12));

 CREATE TABLE "GCG_3613_FREIGHTZONE"(
 "ZONE_ADMISSION" CHAR(17),
 "INBOND_NO" VARCHAR(25),
 "BOL" VARCHAR(35),
 "CBP_SEAL_NO" VARCHAR(10),
 "PACKAGES" INTEGER,
 "US_POU" CHAR(5),
 "FG_POL" CHAR(5),
 "IMPORT_CARRIER" VARCHAR(20),
 "BONDED_CARRIER" CHAR(12),
 "EXPORT_DATE" DATE,
 "IMPORT_DATE" DATE,
 "AIR_FREIGHT" BIT);
 
 CREATE TABLE "GCG_3613_MfgID"(
 "VENDOR" CHAR(6),
 "MFGID" CHAR(15));

 CREATE TABLE "GCG_3613_Mod_Log"(
 "PART" CHAR(17),
 "REV" CHAR(3),
 "LOC" CHAR(2),
 "CONTAINER" VARCHAR(15),
 "MODIFICATION" VARCHAR(6),
 "QUANTITY" NUMERIC(14,5),
 "REASON_CODE" CHAR(2),
 "MOD_DATE" DATE);


CREATE TABLE "GCG_3613_QTY_LOG"(
 "ORDER_NO" CHAR(7),
 "ORDER_SUFFIX" CHAR(4),
 "ITEM" CHAR(4),
 "CONTAINER" VARCHAR(15),
 "PURCHASE_ORDER" CHAR(7),
 "LINE" CHAR(4),
 "PART" CHAR(17),
 "REV" CHAR(3),
 "LOC" CHAR(2),
 "QUANTITY" NUMERIC(14,5));
 
 CREATE TABLE "GCG_3613_Reasons"(
 "CODE" CHAR(2),
 "TEXT" VARCHAR(30));


CREATE TABLE "GCG_3613_ShipHist"(
 "PACKING_NO" CHAR(50),
 "ORDER_NO" CHAR(50),
 "FG_PART" CHAR(50),
 "FG_QTY" NUMERIC(8,2),
 "COMP_PART" CHAR(50),
 "COMP_QTY" NUMERIC(8,2),
 "FREIGHTZONE" CHAR(50),
 "SHIP_USER" CHAR(50),
 "DATE" DATE);

 
 CREATE TABLE "GCG_3613_ShipQty"(
 "Part" CHAR(17),
 "Rev" CHAR(3),
 "Location" CHAR(2),
 "Qty" DOUBLE);
 
 CREATE TABLE "GCG_3613_ShipQtyZZ"(
 "Part" CHAR(17) NOT NULL ,
 "Rev" CHAR(3),
 "Location" CHAR(2),
 "Qty" DOUBLE,
 "BIRUNID" BIGINT,
 "USAGE" NUMERIC(20,2));

CREATE TABLE "GCG_3613_Taxes_Paid"(
 "PART" CHAR(17),
 "REV" CHAR(3),
 "LOC" CHAR(2),
 "QTY" INTEGER);


 CREATE TABLE "GCG_3613_ZONEPARTS"(
 "CONTAINER" VARCHAR(15),
 "PURCHASE_ORDER" CHAR(7),
 "LINE" CHAR(4),
 "PART" CHAR(17),
 "REV" CHAR(3),
 "LOC" CHAR(2),
 "QTY_IN_INV" NUMERIC(14,5));