CREATE TABLE "GCG_3613_QTY_LOG"(
 "ORDER_NO" CHAR(7),
 "ORDER_SUFFIX" CHAR(4),
 "ITEM" CHAR(4),
 "CONTAINER" VARCHAR(15),
 "PURCHASE_ORDER" CHAR(7),
 "LINE" CHAR(4),
 "PART" CHAR(17),
 "REV" CHAR(3),
 "LOC" CHAR(2),
 "QUANTITY" NUMERIC(14,5));