CREATE TABLE "GCG_3613_ShipHist"(
 "PACKING_NO" CHAR(50),
 "ORDER_NO" CHAR(50),
 "FG_PART" CHAR(50),
 "FG_QTY" NUMERIC(8,2),
 "COMP_PART" CHAR(50),
 "COMP_QTY" NUMERIC(8,2),
 "FREIGHTZONE" CHAR(50),
 "SHIP_USER" CHAR(50),
 "DATE" DATE);
