CREATE TABLE "GCG_3613_FREIGHTZONE"(
 "ZONE_ADMISSION" CHAR(17),
 "INBOND_NO" VARCHAR(25),
 "BOL" VARCHAR(35),
 "CBP_SEAL_NO" VARCHAR(10),
 "PACKAGES" INTEGER,
 "US_POU" CHAR(5),
 "FG_POL" CHAR(5),
 "IMPORT_CARRIER" VARCHAR(20),
 "BONDED_CARRIER" CHAR(12),
 "EXPORT_DATE" DATE,
 "IMPORT_DATE" DATE,
 "AIR_FREIGHT" BIT);